# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Caleb Sayre
email: DrSayre2002@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
  A website that will feature neat, interesting, and/or cool things
  as determined by me.  Posts will feature (but not limited to)
  tutorials on web frameworks and other technologies, TV shows, and reviews of that crazy fast food item
  you just saw a commercial for.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://calebsayre.xyz" # the base hostname & protocol for your site
twitter_username: DrSayre
github_username:  DrSayre

# Build settings
markdown: kramdown
theme: minima
disqus_shortname: calebsayre
